version: '3.7'

services:

  food-tracker-front:
    stdin_open: true
    tty: true
    container_name: food-tracker-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true